[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200

# Permit Foundry cheatcodes (vm.readFile, etc.) to access JSON config files
# Add any other folders you want scripts/tests to read from.
fs_permissions = [{ access = "read", path = "./deployments" }]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[lint]
exclude_lints = [
    "unaliased-plain-import",
    "mixed-case-function",
    "screaming-snake-case-const",
    "erc20-unchecked-transfer",
]
